// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQGtVMnV6wn73td5VeCDBN7vkCgNm4aY',
    appId: '1:81452280117:web:c6550d3a3cb3ca8c4a447c',
    messagingSenderId: '81452280117',
    projectId: 'flutter-aa875',
    authDomain: 'flutter-aa875.firebaseapp.com',
    storageBucket: 'flutter-aa875.appspot.com',
    measurementId: 'G-BFR1C1T3CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9G9-c5xWCk-TJ4A-IqU-PO15BbA8zw0',
    appId: '1:81452280117:android:b23ebdfe6d25dc804a447c',
    messagingSenderId: '81452280117',
    projectId: 'flutter-aa875',
    storageBucket: 'flutter-aa875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSkmKAU8oUIyrQul-H9_ReT9kGWgrItGA',
    appId: '1:81452280117:ios:da2dcac81a4d59d64a447c',
    messagingSenderId: '81452280117',
    projectId: 'flutter-aa875',
    storageBucket: 'flutter-aa875.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSkmKAU8oUIyrQul-H9_ReT9kGWgrItGA',
    appId: '1:81452280117:ios:da2dcac81a4d59d64a447c',
    messagingSenderId: '81452280117',
    projectId: 'flutter-aa875',
    storageBucket: 'flutter-aa875.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQGtVMnV6wn73td5VeCDBN7vkCgNm4aY',
    appId: '1:81452280117:web:4036728007a5e2c04a447c',
    messagingSenderId: '81452280117',
    projectId: 'flutter-aa875',
    authDomain: 'flutter-aa875.firebaseapp.com',
    storageBucket: 'flutter-aa875.appspot.com',
    measurementId: 'G-D3X6GDBDLJ',
  );
}
